
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: x509-auth-app
  labels:
    app: x509-auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: x509-auth-app
  template:
    metadata:
      labels:
        app: x509-auth-app
    spec:
      containers:
        - name: x509-auth-app
          image: pnyak/mssltest:latest
          imagePullPolicy: Always
          command:
          - java
          - -Djavax.net.debug=all
          - -jar
          - /app/msslserver.jar
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 50 #Spring boot, faaarkkk
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 50 #Spring boot, faaarkkk
            periodSeconds: 15
          volumeMounts:
            - mountPath: /app/truststore.jks
              name: jks
              subPath: truststore.jks
            - mountPath: /app/keystore.jks
              name: jks
              subPath: keystore.jks
      volumes:
      - name: jks
        secret:
          secretName: jks
